name: Docker registry
on:
  workflow_dispatch:
    inputs:
      version:
        description: Set linode-cli version
        required: true

env:
  DOCKER_USER: ${{ secrets.docker_username }}
  DOCKER_PASS: ${{ secrets.docker_token }}
  VER: ${{ github.event.inputs.version }}

jobs:
  deploy:
    name: Push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}
      - name: Build and push with tag ${{ env.VER }}
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: moleszek/linodecli:${{ env.VER }}
      - name: Build and push with tag latest
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: moleszek/linodecli:latest
