name: Docker registry
on:
  workflow_dispatch:
    inputs:
      version:
        description: Set linode-cli version
        required: true

env:
  DOCKER_USER: ${{ secrets.docker_username }}
  DOCKER_PASS: ${{ secrets.docker_token }}
  VER: ${{ github.event.inputs.version }}
  DISCORD: ${{ secrets.DISCORD_WEBHOOK }}

jobs:
  deploy:
    name: Push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}
      - name: Build and push with tag ${{ env.VER }}
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          tags: moleszek/linodecli:${{ env.VER }}
      - name: Build and push with tag latest
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          tags: moleszek/linodecli:latest
  notify_on_success:
    name: Send notification on success
    needs:
      - deploy
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ env.DISCORD }}
          description: "Successfully built and push docker image to DockerHub!"
  notify_on_failure:
    name: Send notification on failure
    needs:
      - deploy
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ env.DISCORD }}
          status: failure
          description: "Failed to build and push docker image to DockerHub!"
